version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=chat_app
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_app
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

